apiVersion: v1
kind: Secret
metadata:
  name: external-dns-azure
type: Opaque
data:
  azure.json: ewogICAgInRlbmFudElkIjogImUxZmE3YjBiLTU1NzItNDI0ZC1iZWNlLWFkOGM3MzRkMzQ5NiIsCiAgICAic3Vic2NyaXB0aW9uSWQiOiAiNWQyMjlkYWYtM2JhMS00OTMyLTljZTktNjhiMWI1ZjBhNWIyIiwKICAgICJyZXNvdXJjZUdyb3VwIjogImh4LWRzLXAtZG5zLXJnIiwKICAgICJ1c2VXb3JrbG9hZElkZW50aXR5RXh0ZW5zaW9uIjogdHJ1ZQp9
